language: swift
osx_image: xcode10.2
xcode_project: Example.xcodeproj # path to your xcodeproj folder
xcode_scheme: Example
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone Xs

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage

before_script:
  # bootstrap the dependencies for the project
  - cd Example
  - carthage bootstrap --platform iOS